#!/usr/bin/env bash
# Script that transfers the file from the client to a server.
# 4 parameters
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp
# The path to the SSH private key 

if [ "$#" -ne 4 ] ; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $4 $1 $3@$2:/home/$3/$1
fi
